dataset: aloideep3v

encoder_dim:
  - [4096, 1024, 1024, 1024, 128]
  - [2048, 1024, 1024, 1024, 128]

n_classes: 100

epochs: 500
print_freq : 500
batch_size: 1024
momentum: 0.98
temperature: 0.5
alpha: 1
beta: 0.01
blr: 5.0e-4
weight_decay: 0
data_path: ./data/
output_dir: ISP-ACN
seed: 0